[development]
ADMIN_USERNAME = "dijon"
ADMIN_EMAIL = "nobody@jrb.lol"
ADMIN_PASSWORD = "dijon"
TOKEN_EXPIRATION_SECONDS = 7200
TOKEN_ALGORITHM = "HS256"
TOKEN_SECRET_KEY = "64dd5d154eb8f548416c72ae81f323a589b3adab600bd8650cc7ef55ca63f8f6"