"""add rootserver is_enabled column

Revision ID: 024bcf64747e
Revises: e53cce3718c3
Create Date: 2022-11-18 11:37:12.890194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024bcf64747e'
down_revision = 'e53cce3718c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('root_servers', sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('root_servers', 'is_enabled')
    # ### end Alembic commands ###
