"""initial schema

Revision ID: 07d676f0aed7
Revises: 2e5309fed3ad
Create Date: 2022-02-02 15:12:05.794178

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '07d676f0aed7'
down_revision = '2e5309fed3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_servers_id'), 'root_servers', ['id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_server_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['root_server_id'], ['root_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_id'), 'imports', ['id'], unique=False)
    op.create_table('meeting_naws_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_server_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['root_server_id'], ['root_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_naws_codes_id'), 'meeting_naws_codes', ['id'], unique=False)
    op.create_table('service_body_naws_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_server_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['root_server_id'], ['root_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_body_naws_codes_id'), 'service_body_naws_codes', ['id'], unique=False)
    op.create_table('formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_string', sa.String(length=255), nullable=False),
    sa.Column('naws_format_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formats_id'), 'formats', ['id'], unique=False)
    op.create_table('service_bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('helpline', sa.String(length=255), nullable=True),
    sa.Column('world_id', sa.String(length=20), nullable=True),
    sa.Column('service_body_naws_code_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['service_bodies.id'], ),
    sa.ForeignKeyConstraint(['service_body_naws_code_id'], ['service_body_naws_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_bodies_id'), 'service_bodies', ['id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweekenum'), nullable=False),
    sa.Column('service_body_id', sa.Integer(), nullable=False),
    sa.Column('venue_type', sa.Enum('NONE', 'IN_PERSON', 'VIRTUAL', 'HYBRID', name='venuetypeenum'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('time_zone', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=15, scale=12), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=15, scale=12), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('world_id', sa.String(length=20), nullable=True),
    sa.Column('meeting_naws_code_id', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('location_info', sa.Text(), nullable=True),
    sa.Column('location_street', sa.Text(), nullable=True),
    sa.Column('location_city_subsection', sa.Text(), nullable=True),
    sa.Column('location_neighborhood', sa.Text(), nullable=True),
    sa.Column('location_municipality', sa.Text(), nullable=True),
    sa.Column('location_sub_province', sa.Text(), nullable=True),
    sa.Column('location_province', sa.Text(), nullable=True),
    sa.Column('location_postal_code_1', sa.Text(), nullable=True),
    sa.Column('location_nation', sa.Text(), nullable=True),
    sa.Column('train_lines', sa.Text(), nullable=True),
    sa.Column('bus_lines', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('virtual_meeting_link', sa.Text(), nullable=True),
    sa.Column('phone_meeting_number', sa.Text(), nullable=True),
    sa.Column('virtual_meeting_additional_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['meeting_naws_code_id'], ['meeting_naws_codes.id'], ),
    sa.ForeignKeyConstraint(['service_body_id'], ['service_bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('meeting_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_formats_id'), 'meeting_formats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_formats_id'), table_name='meeting_formats')
    op.drop_table('meeting_formats')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_service_bodies_id'), table_name='service_bodies')
    op.drop_table('service_bodies')
    op.drop_index(op.f('ix_formats_id'), table_name='formats')
    op.drop_table('formats')
    op.drop_index(op.f('ix_service_body_naws_codes_id'), table_name='service_body_naws_codes')
    op.drop_table('service_body_naws_codes')
    op.drop_index(op.f('ix_meeting_naws_codes_id'), table_name='meeting_naws_codes')
    op.drop_table('meeting_naws_codes')
    op.drop_index(op.f('ix_imports_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_root_servers_id'), table_name='root_servers')
    op.drop_table('root_servers')
    # ### end Alembic commands ###
