"""initial migration

Revision ID: 2e5309fed3ad
Revises: 
Create Date: 2021-11-10 14:19:55.315296

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2e5309fed3ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('echoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_echoes_id'), 'echoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_echoes_id'), table_name='echoes')
    op.drop_table('echoes')
    # ### end Alembic commands ###
