"""use-enums

Revision ID: 482adb439659
Revises: f064763f709c
Create Date: 2022-02-02 11:29:27.023690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '482adb439659'
down_revision = 'f064763f709c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('day', sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'), nullable=True))
    op.drop_column('meetings', 'weekday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('weekday', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('meetings', 'day')
    # ### end Alembic commands ###
