"""unique naws code

Revision ID: 52279bdc848c
Revises: c6eff75ab4a2
Create Date: 2022-02-09 12:48:26.111238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52279bdc848c'
down_revision = 'c6eff75ab4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'format_naws_codes', ['root_server_id', 'bmlt_id'])
    op.create_unique_constraint(None, 'meeting_naws_codes', ['root_server_id', 'bmlt_id'])
    op.create_unique_constraint(None, 'service_body_naws_codes', ['root_server_id', 'bmlt_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_body_naws_codes', type_='unique')
    op.drop_constraint(None, 'meeting_naws_codes', type_='unique')
    op.drop_constraint(None, 'format_naws_codes', type_='unique')
    # ### end Alembic commands ###
