"""add meeting last_changed field

Revision ID: e53cce3718c3
Revises: 83055e112b14
Create Date: 2022-04-06 12:38:51.186669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53cce3718c3'
down_revision = '83055e112b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('last_changed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'last_changed')
    # ### end Alembic commands ###
