"""add more cascades

Revision ID: f6213afc9933
Revises: b6c96f13ba54
Create Date: 2022-02-03 20:50:49.808879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6213afc9933'
down_revision = 'b6c96f13ba54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meetings_ibfk_3', 'meetings', type_='foreignkey')
    op.drop_constraint('meetings_ibfk_2', 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meetings', 'service_bodies', ['service_body_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key('meetings_ibfk_2', 'meetings', 'service_bodies', ['service_body_id'], ['id'])
    op.create_foreign_key('meetings_ibfk_3', 'meetings', 'snapshots', ['snapshot_id'], ['id'])
    # ### end Alembic commands ###
