#!/usr/bin/env bash

docker run \
  --network=host \
  --env-file=/opt/dijon/compose/dijon.env \
  --env-file=/opt/dijon/compose/dijon.secret.env \
  -e DYNACONF_DBHOST=0.0.0.0 \
  bmltenabled/dijon dijon run-snapshot
