version: '3.8'

services:
  mariadb:
    image: mariadb:10.7.1
    env_file:
      - mariadb.env
    ports:
      - 3306:3306

  dijon:
    image: dijon
    env_file:
      - dijon.env
    expose:
      - 80
